# Generated by Django 5.1 on 2026-05-11 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="Заголовок")),
                ("description", models.TextField(verbose_name="Описание")),
                (
                    "price_per_day",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="Цена за день (₽)"
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        max_length=100, verbose_name="Местоположение (город)"
                    ),
                ),
                (
                    "contact_info",
                    models.TextField(
                        max_length=300, verbose_name="Контактная информация"
                    ),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True, null=True, upload_to="ads/", verbose_name="Фото"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "is_approved",
                    models.BooleanField(
                        default=False, verbose_name="Одобрено модератором"
                    ),
                ),
            ],
            options={
                "verbose_name": "Объявление",
                "verbose_name_plural": "Объявления",
                "ordering": ["-created_at"],
            },
        ),
    ]
