# Generated by Django 6.0.3 on 2026-05-14 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="Название")),
                ("slug", models.SlugField(unique=True, verbose_name="URL")),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
            ],
            options={
                "verbose_name": "Категория",
                "verbose_name_plural": "Категории",
                "ordering": ["name"],
            },
        ),
        migrations.AddField(
            model_name="ad",
            name="available_from",
            field=models.DateField(blank=True, null=True, verbose_name="Доступно с"),
        ),
        migrations.AddField(
            model_name="ad",
            name="available_until",
            field=models.DateField(blank=True, null=True, verbose_name="Доступно до"),
        ),
        migrations.AddField(
            model_name="ad",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                related_name="ads",
                to="ads.category",
                verbose_name="Категории",
            ),
        ),
    ]
