# Generated by Django 6.0.3 on 2026-05-19 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ads", "0003_category_ad_available_from_ad_available_until_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ad",
            name="contact_info",
        ),
        migrations.AddField(
            model_name="ad",
            name="email",
            field=models.EmailField(
                blank=True,
                help_text="example@mail.ru",
                max_length=254,
                verbose_name="Email",
            ),
        ),
        migrations.AddField(
            model_name="ad",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="Формат: +7 (123) 456-78-90",
                max_length=20,
                verbose_name="Телефон",
            ),
        ),
    ]
